import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Oswald } from "next/font/google";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import ExerciseProvider from "@/context/ExerciseProvider";
import { ToastContainer } from "react-toastify";

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "FITLOG — Workout Library",
  description: "Generated by FITLOG",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${oswald.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#0c0d10] text-white">
        <ExerciseProvider>
          <Navbar></Navbar>
          <main>{children}</main>
          <Footer></Footer>
        </ExerciseProvider>
        <ToastContainer autoClose={3000} className={"mt-15"} />
      </body>
    </html>
  );
}
