import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "My Plan | FitLog",
  description: "Generated by FITLOG",
};

export default function MyPlanLayout({
  children,
}: LayoutProps<"/myPlan">) {
  return (
    <>
      {children}
    </>
  );
}
